spring:
  application:
    name: eureka-erver1
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/seata_account?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
  main:
    allow-bean-definition-overriding: true
server:
  port: 8761
  tomcat:
    max-connections: 10000
    max-threads: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    registry-fetch-interval-seconds: 5
    # 不向eureka注册自己
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
