#spring:
#  application:
#    name: order
#暴露所有url
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#  #zipkin-server地址
#  zipkin:
#    base-url: http://localhost:9411/
#  #接口默认全部采样
#  sleuth:
#    sampler:
#      probability: 1.0
##  #指定config服务端的service_id
#  cloud:
#    config:
#      discovery:
#        service-id: config
#      label: master
#      uri: http://localhost:9005
#      profile: stage
#eureka:
#  client:
#    serviceUrl:
#      #注册的地址
#      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
#  instance:
#    #注册的名称
#    instance-id: order
##配置开启hystrix
#feign:
#  hystrix:
#    enabled: true
#  httpclient:
#    enabled: true


